apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-kglycewp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/go-kglycewp:486efdd33df665e0ae72fca0f9d40b98c3f9bb68@sha256:69564ea0d081462a0e52c5947e6680cabeb024b9cdded10f7d6d8f8421887094
          name: container-image
